<a href="https://colab.research.google.com/github/RicardoVilla0/MachineLearning/blob/main/Unidad%202/practica_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Asignatura: Machine Learning

Unidad 2

Docente: Jose Gabriel Rodriguez Rivas

Alumno: Ochoa Villa Ricardo Aron

Practica 1: Evaluar Dataset

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression

In [ ]:
df = pd.read_csv('autos2.csv')
df.head()

symboling  normalized-losses         make fuel-type aspiration  \
0          3                122  alfa-romero       gas        std   
1          3                122  alfa-romero       gas        std   
2          1                122  alfa-romero       gas        std   
3          2                164         audi       gas        std   
4          2                164         audi       gas        std   

  num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0          two  convertible          rwd           front        88.6  ...   
1          two  convertible          rwd           front        88.6  ...   
2          two    hatchback          rwd           front        94.5  ...   
3         four        sedan          fwd           front        99.8  ...   
4         four        sedan          4wd           front        99.4  ...   

   peak-rpm  city-mpg  highway-L/100km    price city-L/100km fuel-type_code  \
0    5000.0        21         8.703704  13495.0    11.190476              1   
1    5000.0        21         8.703704  16500.0    11.190476              1   
2    5000.0        19         9.038462  16500.0    12.368421              1   
3    5500.0        24         7.833333  13950.0     9.791667              1   
4    5500.0        18        10.681818  17450.0    13.055556              1   

   diesel   gas  fuel-type-map  horsepower-binned  
0   False  True              1                Low  
1   False  True              1                Low  
2   False  True              1             Medium  
3   False  True              1                Low  
4   False  True              1                Low  

[5 rows x 32 columns]

In [ ]:
lm = LinearRegression()
lm

LinearRegression()

In [ ]:
X = df[['highway-L/100km']]
Y = df[['price']]

In [ ]:
lm.fit(X, Y)

LinearRegression()

In [ ]:
Yhat = lm.predict(X)
Yhat[0:5]

array([[15485.52737455],
       [15485.52737455],
       [16643.34931414],
       [12475.19033163],
       [22327.2024721 ]])

In [ ]:
lm.intercept_

array([-14617.84305466])

In [ ]:
lm.coef_

array([[3458.68511314]])

In [ ]:
Yhat = - 821.71316345 * 30 + 38581.394060408405
Yhat

13929.999156908405

In [ ]:
valores = [[30]]
Yhat = lm.predict(valores)
Yhat

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[89142.71033965]])

In [ ]:
valores = [[30], [20], [40], [18], [30], [15]]
Yhat = lm.predict(valores)
Yhat

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[ 89142.71033965],
       [ 54555.85920821],
       [123729.56147109],
       [ 47638.48898192],
       [ 89142.71033965],
       [ 37262.43364249]])

In [ ]:
lm.score (X, Y)

0.6417894513258818

In [ ]:
lm1 = LinearRegression()
lm1

LinearRegression()

In [ ]:
lm1.fit(df[['engine-size']], df[['price']])
lm1

LinearRegression()

In [ ]:
lm1.coef_

array([[166.86001569]])

In [ ]:
lm1.intercept_

array([-7963.33890628])

In [ ]:
yhat1 = lm1.predict(df[['engine-size']])
yhat1

array([[13728.4631336 ],
       [13728.4631336 ],
       [17399.38347881],
       [10224.40280408],
       [14729.62322775],
       [14729.62322775],
       [14729.62322775],
       [14729.62322775],
       [13895.32314929],
       [10057.54278839],
       [10057.54278839],
       [19401.70366711],
       [19401.70366711],
       [19401.70366711],
       [26910.40437322],
       [26910.40437322],
       [26910.40437322],
       [ 2215.1220509 ],
       [ 7054.06250595],
       [ 7054.06250595],
       [ 7054.06250595],
       [ 7054.06250595],
       [ 8388.94263148],
       [ 7054.06250595],
       [ 7054.06250595],
       [ 7054.06250595],
       [ 8388.94263148],
       [12393.58300807],
       [18066.82354158],
       [ 7387.78253733],
       [ 7387.78253733],
       [ 5218.60233334],
       [ 7387.78253733],
       [ 7387.78253733],
       [ 7387.78253733],
       [ 7387.78253733],
       [10391.26281977],
       [10391.26281977],
       [10391.26281977],
       [10391.26281977],


In [ ]:
lm1.predict([[120]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[12059.86297669]])

In [ ]:
lm1.score(df[['engine-size']], df[['price']])

0.7609686443622008

In [ ]:
df[["engine-size", "highway-L/100km","price"]].corr()

engine-size  highway-L/100km     price
engine-size         1.000000         0.783465  0.872335
highway-L/100km     0.783465         1.000000  0.801118
price               0.872335         0.801118  1.000000

In [ ]:
Z = df[['horsepower', 'curb-weight', 'engine-size', 'highway-L/100km']]

In [ ]:
lm.fit(Z, df['price'])

LinearRegression()

In [ ]:
lm.intercept_

np.float64(-14385.634549360107)

In [ ]:
lm.coef_

array([ 36.6377371 ,   3.50038215,  85.37370862, 500.51979785])